name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache Prisma schema
      uses: actions/cache@v2
      with:
        path: node_modules/.prisma
        key: ${{ runner.os }}-prisma-${{ hashFiles('**/prisma/schema.prisma') }}
        restore-keys: |
          ${{ runner.os }}-prisma-


    - name: Generate Prisma client
      run: npx prisma generate  # Using npx to directly run Prisma CLI

    - name: Build project
      run: npm run build --if-present
      env:
        DATABASE_URL: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
        DIRECT_URL: ${{ secrets.DIRECT_URL }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
        NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EDGE_STORE_ACCESS_KEY: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
        EDGE_STORE_SECRET_KEY: ${{ secrets.EDGE_STORE_SECRET_KEY }}
        GITHUB_ID: ${{ secrets.ID_GITHUB }}
        GITHUB_SECRET: ${{ secrets.SECRET_GITHUB }}
        GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}

    - name: Run tests
      run: npm test
      env:
        DATABASE_URL: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
        DIRECT_URL: ${{ secrets.DIRECT_URL }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
        NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EDGE_STORE_ACCESS_KEY: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
        EDGE_STORE_SECRET_KEY: ${{ secrets.EDGE_STORE_SECRET_KEY }}
        GITHUB_ID: ${{ secrets.ID_GITHUB }}
        GITHUB_SECRET: ${{ secrets.SECRET_GITHUB }}
        GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
